# Generated by Django 5.2.5 on 2025-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('AM', 'Anime'), ('C', 'Comedy'), ('CR', 'Crime'), ('D', 'Documentary'), ('DR', 'Drama'), ('FM', 'Family'), ('F', 'Fantasy'), ('HF', 'Historical Fiction'), ('H', 'Horror'), ('M', 'Musical'), ('MS', 'Mystery'), ('N', 'Noir'), ('P', 'Psychological'), ('R', 'Romance'), ('SF', 'Science Fiction'), ('T', 'Thriller'), ('W', 'Western'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
