# Generated by Django 5.2.5 on 2025-08-27 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_create_watchlist'),
        ('main_app', '0007_remove_movie_rating'),
    ]

    operations = [
    ]
